name = "RunwayLib"
uuid = "c31d23ff-e9b5-4186-8ef8-ce4d62614c67"
version = "0.1.0"
authors = ["Romeo Valentin <romeov@stanford.edu>"]

[workspace]
projects = ["test", "benchmark", "juliac", "docs", "notebooks"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LightSumTypes = "f56206fc-af4c-5561-a72a-43fe2ca5a923"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Moshi = "2e0e35c7-a2e4-4343-998d-7ef72827ed2d"
NonlinearSolveBase = "be0214bd-f91f-a760-ac4e-3421ce2b2da0"
NonlinearSolveFirstOrder = "5959db7a-ea39-4486-b5fe-2dd0bf03d60d"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
PolyesterWeave = "1d0040c9-8b98-4ee7-8388-3f51789ca0ad"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProbabilisticParameterEstimators = "0098cf3f-3e1e-4f11-b01c-dd9dec1b3374"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[extensions]
PythonCallExt = "PythonCall"

[compat]
ADTypes = "1.16.0"
BenchmarkTools = "1.6.0"
CEnum = "0.5.0"
CSV = "0.10"
DiffEqBase = "^6.179.0"
DifferentiationInterface = "0.7"
Distributions = "0.25.120"
DocStringExtensions = "0.9.5"
ForwardDiff = "1.2.2"
LightSumTypes = "5.2.1"
LinearAlgebra = "1.11.0"
LinearSolve = "3.25.0 - 3.44.0"
Moshi = "0.3.7"
NonlinearSolveBase = "1.13.0,2"
NonlinearSolveFirstOrder = "1.8.0"
Polyester = "0.7.18"
PolyesterWeave = "0.2.2"
PrecompileTools = "1"
ProbabilisticParameterEstimators = "0.8.3"
PythonCall = "0.9"
Rotations = "1"
SciMLBase = "2.102.1"
StaticArrays = "1"
StaticArraysCore = "1.4.4"
StatsBase = "0.34.5"
TypedTables = "1"
Unitful = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[preferences.LinearSolve]
LoadMKL_JLL = false

[targets]
test = ["Test"]
